-- MySQL Script generated by MySQL Workbench
-- Thu May 19 17:55:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nirs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nirs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nirs` DEFAULT CHARACTER SET utf8 ;
USE `nirs` ;

-- -----------------------------------------------------
-- Table `nirs`.`preprocessing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`preprocessing` (
  `preprocessing_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(450) NOT NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`preprocessing_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nirs`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`person` (
  `person_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(450) NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nirs`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`model` (
  `model_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(450) NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nirs`.`embedding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`embedding` (
  `embedding_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `preprocessing_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  `value` VARBINARY(100) NULL,
  `date_added` DATETIME NULL,
  `embeddingcol` VARCHAR(45) NULL,
  PRIMARY KEY (`embedding_id`),
  INDEX `fk_embedding_person_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_embedding_model1_idx` (`model_id` ASC) VISIBLE,
  INDEX `fk_embedding_preprocessing1_idx` (`preprocessing_id` ASC) VISIBLE,
  CONSTRAINT `fk_embedding_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `nirs`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embedding_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `nirs`.`model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embedding_preprocessing1`
    FOREIGN KEY (`preprocessing_id`)
    REFERENCES `nirs`.`preprocessing` (`preprocessing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
