-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 11:57:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema composite_portrait_recongnition
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema composite_portrait_recongnition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `composite_portrait_recongnition` DEFAULT CHARACTER SET utf8 ;
USE `composite_portrait_recongnition` ;

-- -----------------------------------------------------
-- Table `composite_portrait_recongnition`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `composite_portrait_recongnition`.`person` (
  `person_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `patronymic` VARCHAR(100) NULL,
  `surname` VARCHAR(100) NOT NULL,
  `comment` LONGTEXT NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `composite_portrait_recongnition`.`preprocessing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `composite_portrait_recongnition`.`preprocessing` (
  `preprocessing_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `comment` LONGTEXT NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`preprocessing_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `composite_portrait_recongnition`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `composite_portrait_recongnition`.`model` (
  `model_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `comment` LONGTEXT NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `composite_portrait_recongnition`.`embedding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `composite_portrait_recongnition`.`embedding` (
  `embedding_id` INT NOT NULL,
  `value` VARBINARY(100) NOT NULL,
  `date_added` DATETIME NOT NULL,
  `preprocessing_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  PRIMARY KEY (`embedding_id`),
  INDEX `fk_embedding_preprocessing_idx` (`preprocessing_id` ASC) VISIBLE,
  INDEX `fk_embedding_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_embedding_model1_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_embedding_preprocessing`
    FOREIGN KEY (`preprocessing_id`)
    REFERENCES `composite_portrait_recongnition`.`preprocessing` (`preprocessing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embedding_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `composite_portrait_recongnition`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embedding_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `composite_portrait_recongnition`.`model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `composite_portrait_recongnition`.`preprocessing`
-- -----------------------------------------------------
START TRANSACTION;
USE `composite_portrait_recongnition`;
INSERT INTO `composite_portrait_recongnition`.`preprocessing` (`preprocessing_id`, `name`, `comment`, `date_added`) VALUES (1, 'thumbnail ', 'resize an image', '2022-08-16');

COMMIT;


-- -----------------------------------------------------
-- Data for table `composite_portrait_recongnition`.`model`
-- -----------------------------------------------------
START TRANSACTION;
USE `composite_portrait_recongnition`;
INSERT INTO `composite_portrait_recongnition`.`model` (`model_id`, `name`, `comment`, `date_added`) VALUES (1, 'tensorflow', NULL, '2022-08-16');
INSERT INTO `composite_portrait_recongnition`.`model` (`model_id`, `name`, `comment`, `date_added`) VALUES (2, 'arcface', '', '2022-08-16');

COMMIT;

